// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Picoletes.API.Data;

namespace Picoletes.API.Data.Migrations
{
    [DbContext(typeof(PicoletesContext))]
    [Migration("20210123173508_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Picoletes.API.Models.PedidoRetirada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PedidoRetirada");
                });

            modelBuilder.Entity("Picoletes.API.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidadeForaFreezer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Picoletes.API.Models.UnidadeRetirada", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoProduto")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PedidoRetiradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdEstoque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QtdRetirada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValidadeForaFreezer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PedidoRetiradaId");

                    b.ToTable("UnidadeRetirada");
                });

            modelBuilder.Entity("Picoletes.API.Models.UnidadeRetirada", b =>
                {
                    b.HasOne("Picoletes.API.Models.PedidoRetirada", null)
                        .WithMany("ProdutosRetirados")
                        .HasForeignKey("PedidoRetiradaId");
                });
#pragma warning restore 612, 618
        }
    }
}
