// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Picoletes.API.Data;

namespace Picoletes.API.Data.Migrations
{
    [DbContext(typeof(PicoletesContext))]
    [Migration("20210123201705_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Picoletes.Core.Models.PedidoRetirada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("qntAFrut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("qntPChoc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("qntPLim")
                        .HasColumnType("INTEGER");

                    b.Property<int>("qntPMor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("qntSChoc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("qntSFloc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("qntSMor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PedidoRetirada");
                });

            modelBuilder.Entity("Picoletes.Core.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValidadeForaFreezer")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
